spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=indicaai;encrypt=true;trustServerCertificate=true
spring.datasource.username=api_indicai_user
spring.datasource.password=api_indicai_user

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

server.port=8080
